### ISSUE TITLE
[Question] Any examples using pretty-text outside of formatic?

### ISSUE THREAD

**Issue by tcosentino** [zapier/formatic#81]
I should be able to hack through it, but do you have any examples or tips on using the pretty-text component outside of formatic?

My problem so far is setting up the config prop to pass to PrettyText. I tried including `default-config.js` to create it but get some import errors. Would you recommend trying to extract the component from formatic to use on my own?

**Comment by jdeal** [comment]
Hey @tcosentino, sorry about the horribly slow reply! It's on our roadmap (but no timeline right now) to do a big refactor of formatic where we'll make all the fields more usable by themselves. They might always need a wrapper `<Formatic>` element though to provide context.

For now...

If I wanted to use a field by itself, I'd just wrap it in a component which owns the config and renders the field you want. So something like:

```js
// Create a default config.
const config = Formatic.createConfig();

const MyField = ({value, onChange}) => {

  const fields = [
    {type: 'pretty-text', key: 'myField'}
  ];

  const onChangeForm = (formValue) => onChange(formValue.myField);

  return (
    <Formatic
        fields={fields}
        value={{key: 'myField', value}
        onChange={onChangeForm}
        config={FormaticConfig}
    />
  )
};
```

You could then wrap that in a higher order component if you wanted to make it easy to create fields of any type. Something like:

```js
const createFieldComponent = (type) => {
  // use code from above to create a component with a specific type and return it
};

const MyPrettyTextField = createFieldComponent('pretty-text');
const MyPrettySelectField = createFieldComponent('pretty-select');
```
