### ISSUE TITLE
Bump dependencies

### ISSUE THREAD

**Issue by ngryman** [zapier/formatic#88]
@zapier/frontend-engineering We might need some fresher dependencies. Now that we have a `package-lock.json` file, Github is able to warn us about vulnerability issues: https://github.com/zapier/formatic/network/dependencies#30304314.

Even if this one does not impact us, it highlights the fact that we may want to bump our dependencies. As we may take a big leap in dependencies version, it would be better than someone that has more knowledge than me on Formatic do so. If one of you feels comfortable with doing that it would be awesome! 🙏

-- EDIT --

PR for `devDependencies`: https://github.com/zapier/formatic/pull/89

**Comment by vitorbal** [comment]
The devDependencies are now bumped and the vulnerability warning that GitHub was showing us doesn't show anymore.

**Comment by efhjones** [comment]
Thanks @vitorbal and @ngryman ! Should we close this issue then?

**Comment by ngryman** [comment]
@efhjones Absolutely!
